sudo: required

language: node_js

node_js:
  - 10.10.0

cache:
  directories:
    - node_modules

before_install:
  - npm prune

before_scipt:
  - export PORT=4000

script: make test

env:
  global:
    - NODE_ENV=production