version: '2'

services:
  opbadges:
    container_name: opbadges
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - OBF_CERT
      - BADGE_MONGO_HOST
      - BADGE_MONGO_PORT
      - BADGE_MONGO_DB
      - BADGE_LOGENTRY_CLIENT
      - BADGE_LOGENTRY_ISSUER
      - BADGE_AUTHORITY
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    restart: on-failure
    links:
      - opbadgedb:mongodb
      
  opbadgedb:
    container_name: opbadgedb
    image: mongo:3.4.4
    volumes:
      - ./data/db:/data/db
    command: --smallfiles
    restart: on-failure
